### PR TITLE
Add gas_price to staking tx & creating app tx

### PR DESCRIPTION
**Pull request by cshcomcom**
Now we can set gas_price during initialization (staking tx & creating app tx)

### CODE REVIEW

**Comment by liayoo** [comment]
Could you update the gas price in the sample config to 500 (min_gas_price)?

**Comment by cshcomcom** [comment]
Looks good! PTAL! @liayoo

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Review by liayoo — APPROVED** [review]
LGTM, thanks!

**Comment by cshcomcom** [comment]
Thanks! Now merging!

**Pull request merged**
